site_name: Serrano Guides
theme:
  name: 'material'
  logo: 'doc_log.png'
  palette:
    primary: 'red'
    accent: 'deep orange'

repo_url: https://github.com/pcpLiu/Serrano
repo_name: Serrano

site_author: pcpLiu
site_description: Serrano Framework Guides
copyright:  Copyright (c) 2017, Zhonghao (Tim) Liu

site_dir: generated_docs/v0.1.2-alpha/guides

google_analytics:
  - 'UA-54280547-7'
  - 'auto'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#usage
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
    version: v0.1.2-alpha


pages:
  - Home: 'index.md'
  - Get started:
    - 'Install': 'Getting started/Install.md'
    - 'Quick Start: SimpleCNN': 'Getting started/Quick Start Simple CNN.md'
    - 'Forward Computation': 'Getting started/Forward Computation.md'
    - 'FAQ': 'Getting started/FAQ.md'
  - Operator list:
    - Serrano operators: 'operators/about.md'
    - Basic:
      - Unary: 'operators/unary.md'
      - Binary: 'operators/binary.md'
      - Reduce: 'operators/reduce.md'
      - Broadcast: 'operators/broadcast.md'
      - Matrix transpose: 'operators/matrix_transpose.md'
      - Matrix Multiplication: 'operators/matrix_mult.md'
    - Neural network:
      - Common: 
        - Fully Connected: 'operators/fully_connected.md'
      - Convolution: 'operators/conv.md'
      - Pooling: 'operators/pooling.md'
      - Activation: 'operators/activation.md'
  - Extensibility:
    - 'Core Concepts':
      - 'Tensor': 'Getting started/Core concepts/Tensor.md'
      - 'Operator': 'Getting started/Core concepts/Operator.md'
      - 'Graph and Symbol': 'Getting started/Core concepts/Graph.md'
    - 'Write your own operators' : 'Extension/Write your own operator.md'
    - 'Write your own optimizers': 'Extension/Write your own optimizer.md'
  - API Reference: 'API/API Reference.md'
  - Contribution: 'Contribution/Contribution.md'