#ifndef SERRANOSCHEMA_READER_H
#define SERRANOSCHEMA_READER_H

/* Generated by flatcc 0.4.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Serrano_Params_Tensor_table *Serrano_Params_Tensor_table_t;
typedef const flatbuffers_uoffset_t *Serrano_Params_Tensor_vec_t;
typedef flatbuffers_uoffset_t *Serrano_Params_Tensor_mutable_vec_t;
typedef const struct Serrano_Params_Params_table *Serrano_Params_Params_table_t;
typedef const flatbuffers_uoffset_t *Serrano_Params_Params_vec_t;
typedef flatbuffers_uoffset_t *Serrano_Params_Params_mutable_vec_t;



struct Serrano_Params_Tensor_table { uint8_t unused__; };

#ifndef Serrano_Params_Tensor_identifier
#define Serrano_Params_Tensor_identifier flatbuffers_identifier
#endif
#define Serrano_Params_Tensor_type_hash ((flatbuffers_thash_t)0xef96688)
#define Serrano_Params_Tensor_type_identifier "\x88\x66\xf9\x0e"
static inline size_t Serrano_Params_Tensor_vec_len(Serrano_Params_Tensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Serrano_Params_Tensor_table_t Serrano_Params_Tensor_vec_at(Serrano_Params_Tensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Serrano_Params_Tensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(Serrano_Params_Tensor)

__flatbuffers_define_string_field(0, Serrano_Params_Tensor, uid, 0)
__flatbuffers_define_vector_field(1, Serrano_Params_Tensor, values, flatbuffers_float_vec_t, 0)

struct Serrano_Params_Params_table { uint8_t unused__; };

#ifndef Serrano_Params_Params_identifier
#define Serrano_Params_Params_identifier flatbuffers_identifier
#endif
#define Serrano_Params_Params_type_hash ((flatbuffers_thash_t)0x21f5b3df)
#define Serrano_Params_Params_type_identifier "\xdf\xb3\xf5\x21"
static inline size_t Serrano_Params_Params_vec_len(Serrano_Params_Params_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Serrano_Params_Params_table_t Serrano_Params_Params_vec_at(Serrano_Params_Params_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Serrano_Params_Params_table_t, vec, i, 0)
__flatbuffers_table_as_root(Serrano_Params_Params)

__flatbuffers_define_vector_field(0, Serrano_Params_Params, tensors, Serrano_Params_Tensor_vec_t, 0)

#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* SERRANOSCHEMA_READER_H */
